lattice_shape: [6, 6]
base:
  class_path: DiagonalGaussianAction
  init_args:
    lattice_shape: ${lattice_shape}
target:
  m_sq: 0.66
  Î»: 0

layers:
  - transform: spline
    transform_kwargs:
      n_segments: 4
      upper_bound: 5
    net: fnn
    net_hidden_shape: [36]
    net_activation: Tanh
    net_final_activation: Tanh
    net_bias: true
    compose: 1

steps: 2000
batch_size: 1000

output: model

optim:
  optimizer: Adam
  optimizer_init:
    lr: 1e-3
  scheduler: CosineAnnealingLR
  scheduler_init:
    T_max: ${steps}
      #scheduler_extra_config:
      #interval: step

