model:
  target:
    lattice: [2, 2]
    m_sq: 1.

  flow:
    transform:
      net:
        channels: [4]
        activation: tanh
    spatial_net:
      channels: [4]
      activation: tanh
      kernel_radius: 1
    n_blocks: 2

train:
  n_steps: 2000
  batch_size: 1000
  log_n_batches: 13
