model:
  target:
    lattice: [6, 6]
    m_sq: 4.

  flow:
    transform:
      net:
        channels: [10]
        activation: tanh
    spatial_net:
      channels: [3]
      activation: identity
      kernel_radius: 3
    n_blocks: 1

train:
  n_steps: 1000
  batch_size: 1000
  log_n_batches: 13
